"""add_retest_logic

Revision ID: 021af507a333
Revises: baa0c0754d77
Create Date: 2026-06-25 00:12:03.670344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021af507a333'
down_revision = 'baa0c0754d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_retest_on_failure', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), server_default='2', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('allow_retest_on_failure')

    # ### end Alembic commands ###
