"""Add shuffle_questions and question_order

Revision ID: 200ab1b34e8b
Revises: a9ecdcc11cd4
Create Date: 2026-06-24 20:00:48.835117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200ab1b34e8b'
down_revision = 'a9ecdcc11cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffle_questions', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_order', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_column('question_order')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('shuffle_questions')

    # ### end Alembic commands ###
