"""add lms course materials

Revision ID: 28e2d5ae5af8
Revises: 3cd7795ef1ad
Create Date: 2026-10-04 17:01:56.249340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e2d5ae5af8'
down_revision = '3cd7795ef1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_materials_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_materials_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_materials_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_course_materials_course_id'))

    op.drop_table('course_materials')
    # ### end Alembic commands ###
