"""Add exam behavior settings

Revision ID: 44e4b5d848bb
Revises: bf567b53c413
Create Date: 2026-06-19 16:46:44.012931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e4b5d848bb'
down_revision = 'bf567b53c413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_question_numbers', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('allow_question_navigation', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_progress_bar', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('auto_submit_on_timeout', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('auto_submit_on_timeout')
        batch_op.drop_column('show_progress_bar')
        batch_op.drop_column('allow_question_navigation')
        batch_op.drop_column('show_question_numbers')

    # ### end Alembic commands ###
