"""Add timezone to Exam model

Revision ID: 7b50130731a8
Revises: 200ab1b34e8b
Create Date: 2026-06-24 22:08:57.976752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b50130731a8'
down_revision = '200ab1b34e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), server_default='Asia/Kolkata', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
