"""add company_groups and company_aliases

Revision ID: 9bfbd187a1a8
Revises: 5e0641db9982
Create Date: 2026-09-09 12:00:47.541388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfbd187a1a8'
down_revision = '5e0641db9982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    with op.batch_alter_table('company_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_groups_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_group_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=150), nullable=False),
    sa.Column('normalized_alias', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_group_id'], ['company_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_aliases_normalized_alias'), ['normalized_alias'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_aliases_normalized_alias'))

    op.drop_table('company_aliases')
    with op.batch_alter_table('company_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_groups_normalized_name'))

    op.drop_table('company_groups')
    # ### end Alembic commands ###
