"""Add restrict_to_time_window

Revision ID: a9ecdcc11cd4
Revises: 444bfc2ede89
Create Date: 2026-06-20 13:01:47.175041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ecdcc11cd4'
down_revision = '444bfc2ede89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restrict_to_time_window', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('restrict_to_time_window')

    # ### end Alembic commands ###
