"""add candidate registration system

Revision ID: baa0c0754d77
Revises: 7b50130731a8
Create Date: 2026-06-24 23:42:56.796062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa0c0754d77'
down_revision = '7b50130731a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'exam_id', name='uix_candidate_email_exam')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_candidate_registration', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('require_candidate_registration')

    op.drop_table('candidate_registrations')
    # ### end Alembic commands ###
