"""
AIQM LMS Extractor  (stub)
============================
Handles PDFs and exports generated by the AIQM LMS itself.

Status: ARCHITECTURE STUB
  - Detection routes AIQM-branded documents here.
  - Falls back to TextPdfExtractor + Word extractor for now.
  - Full implementation (structured JSON payload, metadata fields) deferred.
"""

from __future__ import annotations

import logging
import os

from app.services.import_engine.extractors.base import BaseExtractor
from app.services.import_engine.extractors.text_pdf_extractor import TextPdfExtractor
from app.services.import_engine.extractors.word_extractor import WordExtractor
from app.services.import_engine.models import (
    DocumentType,
    ExtractionResult,
)

logger = logging.getLogger(__name__)

_PARTIAL_MSG = (
    "AIQM LMS extractor is partially implemented. "
    "Results were produced using generic text extraction. "
    "Review all questions carefully before confirming import."
)


class AiqmLmsExtractor(BaseExtractor):
    extractor_name = "aiqm_lms"

    def extract(self, filepath: str) -> ExtractionResult:
        result = self._make_result(DocumentType.AIQM_LMS)
        result.extractor_name = self.extractor_name
        result.warnings.append(_PARTIAL_MSG)

        ext = os.path.splitext(filepath)[1].lower()

        # Route to best available fallback
        if ext in (".docx", ".doc"):
            fallback = WordExtractor().extract(filepath)
        else:
            fallback = TextPdfExtractor().extract(filepath)

        result.questions = fallback.questions
        result.total_pages = fallback.total_pages
        result.errors.extend(fallback.errors)
        result.warnings.extend(fallback.warnings)
        result.metadata.update(fallback.metadata)

        logger.info(
            "AiqmLmsExtractor: extracted %d questions (fallback mode)",
            len(result.questions),
        )
        return result
